version: '3.7'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "9999:5432"
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    volumes:
      - postgres-data:/var/lib/postgresql

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    labels:
      - "traefik.enable=false"

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-storage:/var/lib/loki
    labels:
      - "traefik.enable=false"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "14268:14268"
      - "16686:16686"

volumes:
  postgres-data:
  grafana-storage:
  loki-storage:
