// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"weeee9/wire-example/model"
	"weeee9/wire-example/router"
	"weeee9/wire-example/service"
)

// Injectors from wire.go:

func InitializeApp() (*app, error) {
	engine, err := model.NewEngine()
	if err != nil {
		return nil, err
	}
	userRepository := model.NewUserRepository(engine)
	userService := service.NewUserService(userRepository)
	userHandler := router.NewUserHandler(userService)
	handler := router.NewRouter(userHandler)
	mainApp := NewApp(handler)
	return mainApp, nil
}
