// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"weeee9/wire-example/config"
	"weeee9/wire-example/middleware/otel-xorm"
	"weeee9/wire-example/model"
	"weeee9/wire-example/router"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitializeApp(cfg config.Config) (*app, error) {
	hook := otelxorm.NewTracingHook()
	engine, err := NewEngine(cfg, hook)
	if err != nil {
		return nil, err
	}
	userRepository := model.NewUserRepository(engine)
	userHandler := router.NewUserHandler(userRepository)
	handler := router.NewRouter(userHandler)
	mainApp := NewApp(handler)
	return mainApp, nil
}
